# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: path_data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='path_data.proto',
  package='cyberdog_controller',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0fpath_data.proto\x12\x13\x63yberdog_controller\x1a\x19google/protobuf/any.proto\"\x94\x03\n\x08PathData\x12:\n\x08left_top\x18\x01 \x01(\x0b\x32(.cyberdog_controller.PathData.TrackPoint\x12;\n\tright_top\x18\x02 \x01(\x0b\x32(.cyberdog_controller.PathData.TrackPoint\x12;\n\tfront_mid\x18\x03 \x01(\x0b\x32(.cyberdog_controller.PathData.TrackPoint\x12<\n\x08\x66\x61rthest\x18\x04 \x01(\x0b\x32*.cyberdog_controller.PathData.FarthestInfo\x1a\"\n\nTrackPoint\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x1ap\n\x0c\x46\x61rthestInfo\x12\x37\n\x05point\x18\x01 \x01(\x0b\x32(.cyberdog_controller.PathData.TrackPoint\x12\x10\n\x08\x64istance\x18\x02 \x01(\x05\x12\x15\n\ris_horizontal\x18\x03 \x01(\x08\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])




_PATHDATA_TRACKPOINT = _descriptor.Descriptor(
  name='TrackPoint',
  full_name='cyberdog_controller.PathData.TrackPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='cyberdog_controller.PathData.TrackPoint.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='cyberdog_controller.PathData.TrackPoint.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=324,
  serialized_end=358,
)

_PATHDATA_FARTHESTINFO = _descriptor.Descriptor(
  name='FarthestInfo',
  full_name='cyberdog_controller.PathData.FarthestInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='point', full_name='cyberdog_controller.PathData.FarthestInfo.point', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='distance', full_name='cyberdog_controller.PathData.FarthestInfo.distance', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_horizontal', full_name='cyberdog_controller.PathData.FarthestInfo.is_horizontal', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=360,
  serialized_end=472,
)

_PATHDATA = _descriptor.Descriptor(
  name='PathData',
  full_name='cyberdog_controller.PathData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='left_top', full_name='cyberdog_controller.PathData.left_top', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='right_top', full_name='cyberdog_controller.PathData.right_top', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='front_mid', full_name='cyberdog_controller.PathData.front_mid', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='farthest', full_name='cyberdog_controller.PathData.farthest', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_PATHDATA_TRACKPOINT, _PATHDATA_FARTHESTINFO, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=472,
)

_PATHDATA_TRACKPOINT.containing_type = _PATHDATA
_PATHDATA_FARTHESTINFO.fields_by_name['point'].message_type = _PATHDATA_TRACKPOINT
_PATHDATA_FARTHESTINFO.containing_type = _PATHDATA
_PATHDATA.fields_by_name['left_top'].message_type = _PATHDATA_TRACKPOINT
_PATHDATA.fields_by_name['right_top'].message_type = _PATHDATA_TRACKPOINT
_PATHDATA.fields_by_name['front_mid'].message_type = _PATHDATA_TRACKPOINT
_PATHDATA.fields_by_name['farthest'].message_type = _PATHDATA_FARTHESTINFO
DESCRIPTOR.message_types_by_name['PathData'] = _PATHDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PathData = _reflection.GeneratedProtocolMessageType('PathData', (_message.Message,), dict(

  TrackPoint = _reflection.GeneratedProtocolMessageType('TrackPoint', (_message.Message,), dict(
    DESCRIPTOR = _PATHDATA_TRACKPOINT,
    __module__ = 'path_data_pb2'
    # @@protoc_insertion_point(class_scope:cyberdog_controller.PathData.TrackPoint)
    ))
  ,

  FarthestInfo = _reflection.GeneratedProtocolMessageType('FarthestInfo', (_message.Message,), dict(
    DESCRIPTOR = _PATHDATA_FARTHESTINFO,
    __module__ = 'path_data_pb2'
    # @@protoc_insertion_point(class_scope:cyberdog_controller.PathData.FarthestInfo)
    ))
  ,
  DESCRIPTOR = _PATHDATA,
  __module__ = 'path_data_pb2'
  # @@protoc_insertion_point(class_scope:cyberdog_controller.PathData)
  ))
_sym_db.RegisterMessage(PathData)
_sym_db.RegisterMessage(PathData.TrackPoint)
_sym_db.RegisterMessage(PathData.FarthestInfo)


# @@protoc_insertion_point(module_scope)
