# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mini_rpc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mini_rpc.proto',
  package='cyberdog_controller',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0emini_rpc.proto\x12\x13\x63yberdog_controller\x1a\x19google/protobuf/any.proto\"D\n\x0eMiniRpcRequest\x12\x0e\n\x06method\x18\x01 \x01(\t\x12\"\n\x04\x61rgs\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any\"S\n\x0fMiniRpcResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0c\n\x04info\x18\x02 \x01(\t\x12\"\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x14.google.protobuf.Anyb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])




_MINIRPCREQUEST = _descriptor.Descriptor(
  name='MiniRpcRequest',
  full_name='cyberdog_controller.MiniRpcRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='method', full_name='cyberdog_controller.MiniRpcRequest.method', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='args', full_name='cyberdog_controller.MiniRpcRequest.args', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=134,
)


_MINIRPCRESPONSE = _descriptor.Descriptor(
  name='MiniRpcResponse',
  full_name='cyberdog_controller.MiniRpcResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='cyberdog_controller.MiniRpcResponse.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='info', full_name='cyberdog_controller.MiniRpcResponse.info', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='cyberdog_controller.MiniRpcResponse.data', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=219,
)

_MINIRPCREQUEST.fields_by_name['args'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_MINIRPCRESPONSE.fields_by_name['data'].message_type = google_dot_protobuf_dot_any__pb2._ANY
DESCRIPTOR.message_types_by_name['MiniRpcRequest'] = _MINIRPCREQUEST
DESCRIPTOR.message_types_by_name['MiniRpcResponse'] = _MINIRPCRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MiniRpcRequest = _reflection.GeneratedProtocolMessageType('MiniRpcRequest', (_message.Message,), dict(
  DESCRIPTOR = _MINIRPCREQUEST,
  __module__ = 'mini_rpc_pb2'
  # @@protoc_insertion_point(class_scope:cyberdog_controller.MiniRpcRequest)
  ))
_sym_db.RegisterMessage(MiniRpcRequest)

MiniRpcResponse = _reflection.GeneratedProtocolMessageType('MiniRpcResponse', (_message.Message,), dict(
  DESCRIPTOR = _MINIRPCRESPONSE,
  __module__ = 'mini_rpc_pb2'
  # @@protoc_insertion_point(class_scope:cyberdog_controller.MiniRpcResponse)
  ))
_sym_db.RegisterMessage(MiniRpcResponse)


# @@protoc_insertion_point(module_scope)
